name: Temurin 11

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-jre:
    uses: ./.github/workflows/workflow-docker-build.yml
    with:
      jvm-type: jre
      docker-context: temurin/11
    permissions:
      contents: read
      packages: write

  build-and-push-jdk:
    uses: ./.github/workflows/workflow-docker-build.yml
    with:
      jvm-type: jdk
      docker-context: temurin/11
    permissions:
      contents: read
      packages: write
