name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      jvm-type:
        required: true
        type: string
        description: "'jre' or 'jdk'"
      docker-context:
        required: true
        type: string
        description: Docker Build Context

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/java-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      -
        name: Copy sample app to Docker context dir
        run: cp app/target/app.jar ${{ inputs.docker-context }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      -
        name: Read .env
        id: dotenv
        uses: falti/dotenv-action@a33be0b8cf6a6e6f1b82cc9f3782061ab1022be5 # v1.1.4
        with:
          path: ${{ inputs.docker-context }}/.env
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=(\d+).*,group=1,priority=101,value=${{ steps.dotenv.outputs.java_version }}
            type=raw,priority=102,value=${{ steps.dotenv.outputs.java_version }}
          flavor: |
            latest=false
            suffix=-${{ inputs.jvm-type }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          platforms: amd64,arm64
          context: ${{ inputs.docker-context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JVM_TYPE=${{ inputs.jvm-type }}
            JAVA_VERSION=${{ steps.dotenv.outputs.java_version }}
