name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      jvm-type:
        required: true
        type: string
        description: "'jre' or 'jdk'"
      docker-context:
        required: true
        type: string
        description: Docker Build Context

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/java-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      -
        name: Copy sample app to Docker context dir
        run: cp app/target/app.jar ${{ inputs.docker-context }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0
      -
        name: Read .env
        id: dotenv
        uses: falti/dotenv-action@1fd84c8ebe23bc2523c13de6cd1ab8a26e6571e5 # v1.0.4
        with:
          path: ${{ inputs.docker-context }}/.env
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=(\d+).*,group=1,priority=101,value=${{ steps.dotenv.outputs.java_version }}
            type=raw,priority=102,value=${{ steps.dotenv.outputs.java_version }}
          flavor: |
            latest=false
            suffix=-${{ inputs.jvm-type }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          platforms: amd64,arm64
          context: ${{ inputs.docker-context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JVM_TYPE=${{ inputs.jvm-type }}
            JAVA_VERSION=${{ steps.dotenv.outputs.java_version }}
